[versions]
agp = "8.9.0"
androidAdvancedwebview = "v3.2.1"
appcompat = "1.2.0"
appupdater = "2.2.1"
attribouter = "0.1.9"
benManesVersions = "0.51.0"
biometric = "1.0.1"
cardview = "1.0.0"
cepaslib = "2.4.5"
circleprogress = "1.2.1"
colorpicker = "0.0.15"
commonsIo = "2.16.1"
commonsLang3 = "3.14.0"
constraintlayout = "2.1.1"
core = "0.9.6.0"
coreKtx = "1.3.2"
coreVersion = "3.5.3"
espressoCore = "3.3.0"
eventbus = "3.3.1"
firebaseBom = "25.9.0"
firebaseCrashlytics = "2.9.9"
flexbox = "3.0.0"
floatingactionbutton = "1.10.1"
fragmentKtx = "1.3.4"
googleServices = "4.4.0"
gson = "2.11.0"
helperlib = "2.3.1"
jsoup = "1.18.1"
junit = "4.13.2"
junitKtx = "1.2.1"
kotlin = "1.9.22"
material = "1.3.0-alpha02"
materialscrollbar = "13.3.4"
mpandroidchart = "v3.0.2"
multidex = "2.0.1"
legacySupportV4 = "1.0.0"
paletteKtx = "1.0.0"
picasso = "2.71828"
playServicesAuth = "18.1.0"
playServicesSafetynet = "17.0.0"
playServicesVision = "20.1.1"
preferenceKtx = "1.1.1"
rules = "1.3.0"
sonarqube = "4.4.1.3373"
sqldelight = "2.0.1"
viewpager2 = "1.0.0"

[libraries]
android-advancedwebview = { module = "com.github.delight-im:Android-AdvancedWebView", version.ref = "androidAdvancedwebview" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
appupdater = { module = "com.itachi1706.appupdater:appupdater", version.ref = "appupdater" }
attribouter = { module = "me.jfenn:Attribouter", version.ref = "attribouter" }
biometric = { module = "androidx.biometric:biometric", version.ref = "biometric" }
cardview = { module = "androidx.cardview:cardview", version.ref = "cardview" }
cepaslib = { module = "com.itachi1706.cepaslib:cepaslib", version.ref = "cepaslib" }
circleprogress = { module = "com.github.lzyzsd:circleprogress", version.ref = "circleprogress" }
colorpicker = { module = "com.github.QuadFlask:colorpicker", version.ref = "colorpicker" }
commons-lang3 = { module = "org.apache.commons:commons-lang3", version.ref = "commonsLang3" }
commons-io = { module = "commons-io:commons-io", version.ref = "commonsIo" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
core = { module = "com.afollestad.material-dialogs:core", version.ref = "core" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
eventbus = { module = "org.greenrobot:eventbus", version.ref = "eventbus" }
firebase-analytics-ktx = { module = "com.google.firebase:firebase-analytics-ktx" }
firebase-auth-ktx = { module = "com.google.firebase:firebase-auth-ktx" }
firebase-config-ktx = { module = "com.google.firebase:firebase-config-ktx" }
firebase-core = { module = "com.google.firebase:firebase-core" }
firebase-crashlytics-ktx = { module = "com.google.firebase:firebase-crashlytics-ktx" }
firebase-database-ktx = { module = "com.google.firebase:firebase-database-ktx" }
firebase-ml-vision = { module = "com.google.firebase:firebase-ml-vision" }
firebase-perf = { module = "com.google.firebase:firebase-perf" }
floatingactionbutton = { module = "com.getbase:floatingactionbutton", version.ref = "floatingactionbutton" }
fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragmentKtx" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
helperlib = { module = "com.itachi1706.helpers:helperlib", version.ref = "helperlib" }
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
junit = { module = "junit:junit", version.ref = "junit" }
junit-ktx = { module = "androidx.test.ext:junit-ktx", version.ref = "junitKtx" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
flexbox = { module = "com.google.android.flexbox:flexbox", version.ref = "flexbox" }
legacy-support-v4 = { module = "androidx.legacy:legacy-support-v4", version.ref = "legacySupportV4" }
material = { module = "com.google.android.material:material", version.ref = "material" }
materialscrollbar = { module = "com.github.turing-tech:MaterialScrollBar", version.ref = "materialscrollbar" }
mpandroidchart = { module = "com.github.PhilJay:MPAndroidChart", version.ref = "mpandroidchart" }
multidex = { module = "androidx.multidex:multidex", version.ref = "multidex" }
palette-ktx = { module = "androidx.palette:palette-ktx", version.ref = "paletteKtx" }
picasso = { module = "com.squareup.picasso:picasso", version.ref = "picasso" }
play-services-auth = { module = "com.google.android.gms:play-services-auth", version.ref = "playServicesAuth" }
play-services-safetynet = { module = "com.google.android.gms:play-services-safetynet", version.ref = "playServicesSafetynet" }
play-services-vision = { module = "com.google.android.gms:play-services-vision", version.ref = "playServicesVision" }
preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preferenceKtx" }
rules = { module = "androidx.test:rules", version.ref = "rules" }
viewpager2 = { module = "androidx.viewpager2:viewpager2", version.ref = "viewpager2" }
zxing-core = { module = "com.google.zxing:core", version.ref = "coreVersion" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
benmanes-versions = { id = "com.github.ben-manes.versions", version.ref = "benManesVersions" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebaseCrashlytics" }
google-services = { id = "com.google.gms.google-services", version.ref = "googleServices" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
sonarqube = { id = "org.sonarqube", version.ref = "sonarqube" }
sqldelight = { id = "app.cash.sqldelight", version.ref = "sqldelight" }
